### PR TITLE
Deployment diagram

### LINKED ISSUE #2: Deployment Diagram
Current deployment diagram. Source is on Google Drive for now.

image

### PR DESCRIPTION
**Pull request by egeldenhuys**
Closes #2 

## Original Diagram
deployment-diagram

## Latest Diagram
deployment-diagram

### CODE REVIEW

**Comment by devosray** [comment]
The deployment diagram suggests that the browser directly connects to the API. Shouldn't there be some kind of authentication/fileserver in the Docker swarm as well? There should still be an HTTPS link from the browser to the API but right now the diagram indicates the API will serve the frontend. Is this intended?

**Comment by egeldenhuys** [comment]
> There should still be an HTTPS link from the browser to the API but right now the diagram indicates the API will serve the frontend.

What do you mean with "serve"?

**Comment by devosray** [comment]
> What do you mean with "serve"?

Where will the browser (client) download the HTML/JS/CSS files needed for the frontend? There should be some kind of server (NGINX, Node, python http.server) that will `serve` the contents. Right now, the diagram shows the API responsible for the REST interface also serving the static frontend assets. Is this correct?

**Comment by egeldenhuys** [comment]
Above the client I indicated a CDN node, which can be whatever you want it to be: Dropbox folder, GitHub pages, nginx server on the Manager Node or even a distributed delivery network from within the swarm.

#### TODO
- [ ] Indicate where the browser gets it's resources from by means of UML deployment artifacts

**Comment by devosray** [comment]
Ah, if the CDN will serve our files, it should be all good. I approve.

**Comment by egeldenhuys** [comment]
> Shouldn't there be some kind of authentication/fileserver in the Docker swarm as well?
Docker manages the authentication with Public/Private keys. If that is what you are asking.

With HTTPS and the Docks API, I think the best solution would be to use Let's Encrypt and an nginx reverse proxy

**Comment by devosray** [comment]
@egeldenhuys How will we handle the log-in and session management part of the frontend? Will that be part of the Docks API too?

**Comment by egeldenhuys** [comment]
I am thinking about the following process, as part of the Docks API:

1. Client sends username and password to Docks
2. Docks checks database
3. If the credentials are correct we return a session token, otherwise we log the break in attempt
4. The client then uses this token for subsequent requests until it expires

**Comment by egeldenhuys** [comment]
deployment-diagram

**Comment by egeldenhuys** [comment]
> With HTTPS and the Docks API, I think the best solution would be to use Let's Encrypt and an nginx reverse proxy

That scenario works well when you have many virtual hosts and want to register new domains as you start your virtual hosts in Docker.

It might be better to use something like [Daplie/greenlock-express](https://github.com/Daplie/greenlock-express)

**Comment by egeldenhuys** [comment]
We will have to serve the frontend from the same domain as the swarm otherwise we face Cross Origin problems. Or we need to look into CORS

**Comment by Mimels** [comment]
That is where Raymond and I come in! Thanks COS216. There are various ways of circumventing it or we can try and avoiding it completely.

**Comment by egeldenhuys** [comment]
@Mimels , Great! After the demo we will document the solution

**Pull request merged**
